# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1f93d9b52cf9382f8a4c6e3e5c8678e2551d90f06a31a78c0b1ba9a191673c549b46374847f86b89e824156646a32c952d8139a013033616b4f0f91d3e623d8

test:
  secret_key_base: 0d315ec8ece120bd80eb8185f65ea714195b7a79d58d5b601336b314c0d78f8606bebaab79f4388e1e32fd0823bf6a334a40f12bb65722945bed99eff8010930

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
